#!/bin/dash

cmds=$1

range=$(echo $cmds > .legit/temp.txt | egrep '^[a-zA-Z0-9]' .legit/temp.txt)
range1=$(echo $cmds > .legit/temp.txt | egrep '[^a-zA-Z0-9._\-]+' .legit/temp.txt)
#Filename Check Only Right First Letter
if [ "$range" = "" ]
    then
    echo "legit-show: error: invalid filename '$cmds'"
    exit 1
fi

if [ "$range1" != "" ]
    then 
    echo "legit-show: error: invalid filename '$cmds'"
    exit 1
fi
