#!/bin/dash

# Getting list of all files from the 3 files
repo=`ls .legit/commits | sort -n -r 2> /dev/null | head -1`
ls > .legit/tempfiles 2> /dev/null
ls .legit/commits/"$repo" >> .legit/tempfiles 2> /dev/null
ls .legit/index >> .legit/templfiles 2> /dev/null
list=`sort -u < .legit/tempfiles 2> /dev/null`

#echo $list

for names in $list
do
	# Name Check	
	cmds=$names
	range=`echo $cmds | egrep '^[a-zA-Z0-9]' 2>&1`
	range1=`echo $cmds | egrep '[^a-zA-Z0-9._\-]+' 2>&1`
	if [ "$range" = "" ]
		then
		continue
	fi

	if [ "$range1" != "" ]
		then 
		continue
	fi	
	
	#Searching Local, Index and Repo
	localindex=`diff $names .legit/index/$names 2>&1`
	localrepo=`diff $names .legit/commits/"$repo"/$names 2>&1`
	indexrepo=`diff .legit/index/$names .legit/commits/"$repo"/$names 2>&1`
	allsame=0
	alldiff=0
	if [ "$localindex" = "" ]
	then
		if [ "$indexrepo" = "" ]
		then
			if [ "$localrepo" = "" ]
			then
				allsame=1
			fi
		fi
	elif [ "$localindex" != "" ]
	then
		if [ "$localindex" != "" ]
		then
			if [ "$indexrepo" != "" ]
			then
				alldiff=1
			fi
		fi
	fi
	
	#Checking if file exists
	emptrepo=0
	emptlocal=0
	emptindex=0
	if test -f $names
	then
		emptlocal=1
	fi
	
	if test -f .legit/index/$names
	then
		emptindex=1
	fi
	
	if test -f .legit/commits/"$repo"/$names
	then
		emptrepo=1
	fi
	
	#Cases if Missing files
	#Empty Local
	if [ $emptindex -eq 1 ]
	then
		if [ $emptrepo -eq 1 ]
		then
			if [ $emptlocal -eq 0 ]
			then
				echo "$names - file deleted"
				continue
			fi
		fi
	fi 
	#Empty Local and Index
	if [ $emptlocal -eq 0 ]
	then
		if [ $emptindex -eq 0 ]
		then
			if [ $emptrepo -eq 1 ]
			then
				echo "$names - deleted"
				continue
			fi
		fi
	fi
	# Same in local and index. Removed in Repo
	if [ "$localindex" = "" ]
	then
		if [ $emptrepo -eq 0 ]
		then
			echo "$names - added to index"
			continue
		fi
	fi
	
	# Different Local and Repo. Empty Index
	if [ "$localrepo" != "" ]
	then
		if [ $emptindex -eq 0 ]
		then
			echo "$names - untracked"
			continue
		fi
	fi
	
	#Exists in local but does not in index and repo 
	if [ $emptlocal -eq 1 ]
	then
		if [ $emptindex -eq 0 ]
		then
			if [ $emptrepo -eq 0 ]
			then
				echo "$names - untracked"
				continue
			fi
		fi
	fi
	
	if [ $alldiff -eq 1 ] 
	then
		echo "$names - file changed, different changes staged for commit"
		continue
	fi
	
	if [ $allsame -eq 1 ]
	then
		echo "$names - same as repo"
		continue
	fi
	
	#Same Local and Index Different Repo
	if [ "$localindex" = "" ]
	then
		if [ "$localrepo" != "" ]
		then
			echo "$names - file changed, changes staged for commit"
			continue
		fi
	fi
	
	#Same Index and Repo. Different Local
	if [ "$indexrepo" = "" ]
	then
		if [ "$localrepo" != "" ]
		then
			echo "$names - file changed, changes not staged for commit"
			continue
		fi
	fi
	
	
	
	
	
	
done
